/*
package study.caiy.com.kotlinstudy

*/
/**
 * Created by admin on 2017/6/1.
 *//*



开始
        基本语法

            定义包
            定义函数
            定义局部变量
            注释
            使用字符串模板
            使用条件表达式
            使用可空值及null检测
            使用类型检测及自动类型转换
            使用for循环
            使用while循环
            使用when表达式
            使用区间（Range）
            使用集合
        习惯用法
            DTOS
            函数的默认参数
            过滤list
            String内插
            类型判断
            遍历map/pair型list
            使用区间
            只读list
            只读map
            访问map
            延迟属性
            扩展函数
            创建单例
            if not null 缩写
            if not null and else 缩写
            返回when表达式
            try catch
            if表达式
            返回类型为Unit的方法的Builder风格用法
            单表达式函数
            对一个对象实例调用多个方法(with)
            java7中的try with resources
            对于需要泛型信息的泛型函数的适宜形式
            使用可空boolean
        编码规范
            命名风格
            冒号
            Lambda表达式
            类头格式化
            Unit
            函数还是属性
基础
        基本类型
            数字
            字符
            布尔
            数组
            字符串
        包
            默认导入
            导入
            顶层声明的可见性
        控制流
            if表达式
            when表达式
            for循环
            while循环
        返回和跳转
            break和continue
            标签处返回
类和对象
        类和继承
            类
            构造函数
            次构造函数
            创建类的实例
            类成员
            继承
                覆盖方法
                覆盖属性
                覆盖规则
            抽象类
            伴生对象
        属性和字段
            声明属性
            getters和setters
            幕后字段
            幕后属性
            编译期常量
            延迟初始化属性
            覆盖属性
            委托属性
        接口
            实现接口
            接口中的属性
            解决覆盖冲突
        可见性修饰符
            包名
            类和接口
            构造函数
            局部声明
            模块
        扩展
        数据类
        密封类
        泛型
        嵌套类
        枚举类
        对象
        委托
        属性函数
*/
